export const landingAssetPaths = {
  heroBg: '/entry-station/hero-bg.jpg',
  storeFrontNew: '/entry-station/store-front-new.jpg',
  aboutImage: '/entry-station/about-img.jpg',
  teamPhoto: '/entry-station/team-photo.jpg',
  equipmentDetail: '/entry-station/equipment-detail.jpg',
  serviceScene: '/entry-station/service-scene.jpg',
  productDetection: '/entry-station/product-detection.jpg',
  productBand: '/entry-station/product-band.jpg',
  productWater: '/entry-station/product-water.jpg',
  franchiseHero: '/entry-station/franchise-hero.jpg',
  successCase1: '/entry-station/success-case-1.jpg',
  lifestyleSmart: '/entry-station/lifestyle-smart.jpg',
  techSpectrum: '/entry-station/tech-spectrum.jpg',
  whyChoose: '/entry-station/why-choose.jpg',
  caseSleep: '/entry-station/case-sleep.jpg',
  casePain: '/entry-station/case-pain.jpg',
  caseEnergy: '/entry-station/case-energy.jpg',
  caseElderly: '/entry-station/case-elderly.jpg',
  caseNeck: '/entry-station/case-neck.jpg',
  caseMenopause: '/entry-station/case-menopause.jpg',
  newsAiHealth: '/entry-station/news-ai-health.jpg',
  newsCellRepair: '/entry-station/news-cell-repair.jpg',
  newsAward: '/entry-station/news-award.jpg',
  newsCertification: '/entry-station/news-certification.jpg',
  newsMarket: '/entry-station/news-market.jpg',
  newsOpening: '/entry-station/news-opening.jpg',
} as const;
